### ISSUE TITLE
Request for MIT license

### ISSUE THREAD

**Issue by lacerdamarcelo** [jkwang93/ChemistGA#1]
Hi all!

I'd like to kindly ask you to add an MIT license file to this repository. Without such a license, I'm not allowed to use any part of your code in any of the projects I'm working on at the company I work for. Would that be possible?

An example of an MIT license can be found here: https://github.com/pschwllr/MolecularTransformer/blob/master/LICENSE.md

Thanks a lot!

**Comment by jkwang93** [comment]
Thank you for your interest in our work. MIT license has added.

**Comment by lacerdamarcelo** [comment]
Thanks a lot!
