### ISSUE TITLE
function crossover

### ISSUE THREAD

**Issue by suice07** [jkwang93/ChemistGA#3]
Hello dear Author,

I am quite interested in the your work and wanted to try the code and found that there miss a function(or library) called crossover, could you please tell me how to get it? or what is the function of co.mol_OK/co.ring_OK for . Thanks

**Comment by jkwang93** [comment]
Thank you for your interest in our work. I'm very sorry that we missed it when uploading the code, it has now re-uploaded crossover.py

**Comment by suice07** [comment]
Thanks a lot!
